In [53]:
#Distance Calculation Collective (Written by Chantelle)
import pandas as pd
from pyproj import Geod

#pyproj settings
wgs84_geod = Geod(ellps='WGS84')

#import address data
amenities = pd.read_csv("latlongamenities.csv")
purchase = pd.read_csv("latlongpurchase.csv")

amenities.head(6)

  type                    name       lat        long     region
0  mrt   ADMIRALTY MRT STATION  1.440585  103.800998      north
1  mrt    ALJUNIED MRT STATION  1.316433  103.882893    central
2  mrt  ANG MO KIO MRT STATION  1.369933  103.849553  northeast
3  mrt       BAKAU LRT STATION  1.388093  103.905418  northeast
4  mrt     BANGKIT LRT STATION  1.380018  103.772667       west
5  mrt     BARTLEY MRT STATION  1.342828  103.879746  northeast

In [54]:
#calculate distance with coordinates
def Distance(lat1,lon1,lat2,lon2):
  az12,az21,dist = wgs84_geod.inv(lon1,lat1,lon2,lat2)
  return dist

In [55]:
#df['testlat'] = geolocator.geocode("Singapore").latitude
#df['testlon'] = geolocator.geocode("Singapore").longitude

testlat = purchase['lat'].to_list()
testlon = purchase['long'].to_list()
sector = purchase['sector'].to_list()

i = 0

while i < len(testlat):
    amenities['testlat'] = testlat[i]
    amenities['testlon'] = testlon[i]
    name = "sector" + str(sector[i])
    amenities[name] = Distance(amenities['lat'],amenities['long'],amenities['testlat'],amenities['testlon'])/1000
    amenities = amenities.drop(['testlat','testlon'], axis=1)
    i += 1
    
amenities

,type,name,lat,long,region,sector1,sector2,sector3,sector4,sector5,...,sector109,sector110,sector111,sector112,sector113,sector114,sector115,sector116,sector117,sector118
0,mrt,ADMIRALTY MRT STATION,1.440585,103.800998,north,18.168550,17.968647,17.404337,16.662711,17.654438,...,13.547305,14.187464,16.914185,14.790601,11.625740,16.617069,3.230206,24.727158,21.512236,18.599559
1,mrt,ALJUNIED MRT STATION,1.316433,103.882893,central,5.084560,5.183606,4.489700,3.260771,3.990698,...,6.145435,11.224428,10.824390,14.675736,15.267481,20.047387,13.629997,24.461263,9.215542,14.159875
2,mrt,ANG MO KIO MRT STATION,1.369933,103.849553,northeast,9.501596,9.373260,8.677362,7.659173,8.739092,...,5.915571,9.749949,11.234451,12.448379,11.361674,16.974765,6.687968,23.366790,13.485351,13.817470
3,mrt,BAKAU LRT STATION,1.388093,103.905418,northeast,13.031334,13.041499,12.276784,10.974459,11.976126,...,11.374380,16.002981,16.968606,18.911736,17.870798,23.505889,9.772450,29.757231,17.302209,7.295832
4,mrt,BANGKIT LRT STATION,1.380018,103.772667,west,13.701336,13.438931,13.114892,12.877594,13.592717,...,8.955276,7.407382,10.348583,7.410321,4.279639,9.704477,7.769750,17.509950,16.034714,21.824400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,supermarket,I-TEC SUPERMART PTE LTD GEYLANG ROAD,1.313757,103.885492,central,5.097855,5.218292,4.554550,3.379178,4.013208,...,6.464060,11.509557,11.021444,14.968309,15.619918,20.355450,14.026932,24.667422,9.154782,14.201210
1171,supermarket,YEO HOCK HENG ALJUNIED ROAD,1.323423,103.881329,central,5.546891,5.612115,4.880483,3.591454,4.456250,...,5.955347,11.098482,10.910703,14.521023,14.932576,19.842571,12.866515,24.504332,9.757461,13.702652
1172,supermarket,AZ SUPERMART PTE. LTD. KAKI BUKIT AVENUE 3,1.306095,103.896091,central,5.631325,5.812146,5.264469,4.293439,4.629785,...,7.771534,12.716999,11.995126,16.186580,16.981953,21.606879,15.344665,25.630144,9.338914,14.189450
1173,supermarket,FOODIE MARKET PLACE PTE. LTD. TANJONG KATONG ROAD,1.306095,103.896091,east,5.631325,5.812146,5.264469,4.293439,4.629785,...,7.771534,12.716999,11.995126,16.186580,16.981953,21.606879,15.344665,25.630144,9.338914,14.189450
1174,supermarket,ZAC MEAT & POULTRY PTE LTD FIGARO STREET,1.316828,103.929346,east,9.495983,9.687356,9.151082,8.145885,8.513601,...,11.303387,16.393759,15.851722,19.845474,20.319818,25.207929,16.645205,29.496916,12.969916,11.433694

In [56]:
#convert data to csv file
amenities.to_csv('distancesamenities.csv', index=False)